version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: whatsapp-postgres
    environment:
      POSTGRES_DB: whatsapp_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - whatsapp-network

  whatsapp-backend:
    build: .
    container_name: whatsapp-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/whatsapp_chat
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    networks:
      - whatsapp-network

volumes:
  postgres_data:

networks:
  whatsapp-network:
    driver: bridge 